edition = "2021"
version = "Two"
hard_tabs = true
max_width = 120
tab_spaces = 4
newline_style = "Unix"

use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true
reorder_impl_items = true

imports_granularity = "Item"
group_imports = "StdExternalCrate"

wrap_comments = true
comment_width = 100
normalize_comments = false

normalize_doc_attributes = true
format_code_in_doc_comments = true